### ISSUE TITLE
BREAKING CHANGE: SqlSetup: Default startup option for the agent service should be Manual instead of Automatic

### ISSUE THREAD

**Issue by mdaniou** [dsccommunity/SqlServerDsc#1198] opened 2018-08-16 14:29 UTC
#### Details of the scenario you tried and the problem that is occurring

Opening an issue to apply change in the resource to remove the code that set the agent service startup to Automatic. The is a breaking change.

#### The DSC configuration that is using the resource (as detailed as possible)

SqlSetup

#### Version of the operating system and PowerShell the target node is running

Windows Server 2012/2012R2/2016

#### SQL Server edition and version the target node is running

SQL Server 2012/2014/2016/2017

#### What SQL Server PowerShell modules, and which version, are present on the target node.

Most recent version

#### Version of the DSC module you're using, or write 'dev' if you're using current dev branch

Most recent version

**Comment by johlju** [comment] 2020-05-14 16:34
Duplicate of issue #464 and was fixed in a recent PR.

**Closed by johlju** 2020-05-14 16:34 UTC
Labels: breaking change, bug, good first issue, help wanted
