### ISSUE TITLE
SqlServiceAccount: Update to correctly handle changing Reporting Services service account

### ISSUE THREAD

**Issue by aleksbor** [dsccommunity/SqlServerDsc#1463] opened 2020-01-14 17:48 UTC
Details of the scenario you tried and the problem that is occurring:
SqlRSSetup does not contain SvcAccount parameter, similar to RSSvcAccount in SQLSetup.

We need to be able to specify a service account during install. 

The DSC configuration that is using the resource (as detailed as possible):
n/a

Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:
Microsoft SQL Server 2017 Reporting Services

What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:
n/a

Version of the DSC module you're using, or 'dev' if you're using current dev branch:
13.2.0.0

**Comment by johlju** [comment] 2020-01-14 18:58
I'm not sure that is possible 🤔Does the setup.exe provide a parameter for setting the account? Otherwise I suggest this need to be changed by another resource, either SqlRS or a new resource depending on what it takes to change the service account.

Can you provide the steps (or link) how to change the service account?

**Comment by aleksbor** [comment] 2020-01-14 22:33
Is there a command line setup? I don't see any MS instructions. Only the "wizard of Microsoft" steps.

**Comment by aleksbor** [comment] 2020-01-15 07:53
Don't believe setup offers that functionality. They call their setup "copy files install" or something of that sort. 
To update the service account Get-WmiObject can be used:
$RSService = Get-WmiObject -ComputerName $sComputerName -Query "SELECT * FROM Win32_Service WHERE Name = 'SQLServerReportingServices'"
$RSService.Change($null,$null,$null,$null,$null,$null,"$sUsername",$sPassword) | Out-Null

**Comment by johlju** [comment] 2020-01-15 14:13
I do not think it is a good idea changing the service account directly in Services.

Looking into this is seems there is a metod `SetWindowsServiceIdentity()` that probably is better. 

>Makes the Report Server Windows service run as a specified Windows user, and grants this account sufficient file system permissions to allow the report server to operate.
>https://docs.microsoft.com/en-us/sql/reporting-services/wmi-provider-library-reference/configurationsetting-method-setwindowsserviceidentity?view=sql-server-ver15

It is part of the `MSReportServer_ConfigurationSetting` class.
https://docs.microsoft.com/en-us/sql/reporting-services/wmi-provider-library-reference/msreportserver-configurationsetting-members?view=sql-server-ver15

See an example of automating using that class. 
https://blog.aelterman.com/2018/01/03/complete-automated-configuration-of-sql-server-2017-reporting-services/

If you could verify it is possible to achieve what you looking for using the method above and provide a snippet of code then it would be easier for the community to add this. Since it is not available as a setup argument I suggest update the resource `SqlServiceAccount` to correctly handle the Reporting Services service account.

You are welcome to send in a pull request for this change.

**Comment by shurick81** [comment] 2020-02-07 22:07
Isn't it a duplicate of https://github.com/dsccommunity/SqlServerDsc/issues/1259 ?

**Comment by johlju** [comment] 2020-02-08 14:02
Yes, it would seem. Closing this and tracking this in the older issue.

**Closed by johlju** 2020-02-08 14:02 UTC
Labels: bug, help wanted
