### ISSUE TITLE
SqlServerDsc: SQL authentication does not work in any resource

### ISSUE THREAD

**Issue by ofaruk09** [dsccommunity/SqlServerDsc#360] opened 2017-02-01 12:16 UTC
$sql = New-Object Microsoft.SqlServer.Management.Smo.Server
        $sql.ConnectionContext.ConnectAsUser = $true
        $sql.ConnectionContext.ConnectAsUserPassword = "myuser"
        $sql.ConnectionContext.ConnectAsUserName = "mypassword"
        $sql.ConnectionContext.ServerInstance = "myinstance"
        $sql.ConnectionContext.connect()
Exception calling "Connect" with "0" argument(s): "The user name or password is incorrect.
"
At line:6 char:9
+         $sql.ConnectionContext.connect()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ConnectionFailureException

I have verified the username and password is correct but it does not work. Using the following code instead did work:

$srvname = "myinstance"
$ServerConnection = new-object Microsoft.SqlServer.Management.Common.ServerConnection
$ServerConnection.ServerInstance=$srvname
$ServerConnection.LoginSecure = $false
$ServerConnection.Login = "myuser"
$ServerConnection.Password = "mypassword"

$sql = new-object Microsoft.SqlServer.Management.SMO.Server($ServerConnection)
$sql.ConnectionContext.connect()

**Comment by johlju** [comment] 2017-02-01 16:55
You are correct. I could reproduced the error. Currently SQL authentication is not supported. Was it SQL authentication that was your issue?

This works for me to impersonate a domain user (the current code).
```
Import-Module SQLPS

$SetupCredential = Get-Credential

$sql = New-Object Microsoft.SqlServer.Management.Smo.Server
$sql.ConnectionContext.ConnectAsUser = $true
$sql.ConnectionContext.ConnectAsUserName = $SetupCredential.GetNetworkCredential().UserName
$sql.ConnectionContext.ConnectAsUserPassword = $SetupCredential.GetNetworkCredential().Password
$sql.ConnectionContext.ServerInstance = 'server.company.local'
$sql.ConnectionContext.Connect()

$sql.Status
```

But to impersonate (or login) as user using SQL authentication, this code needs to be used, as @ofaruk09 proposed above.

```
Import-Module SQLPS

$SetupCredential = Get-Credential

$sql = New-Object Microsoft.SqlServer.Management.Smo.Server
$sql.ConnectionContext.LoginSecure = $false
$sql.ConnectionContext.Login = $SetupCredential.UserName
$sql.ConnectionContext.SecurePassword = $SetupCredential.Password
$sql.ConnectionContext.ServerInstance = 'server.company.local'
$sql.ConnectionContext.Connect()

$sql.Status
```

But how shall we go by and distinguish SQL authentication from domain credentials? Just check if the username contains '\' or '@'? If $true, use the domain account impersonation, if $false, use SQL  authentication.

**Comment by ofaruk09** [comment] 2017-02-01 17:18
The method in question is called by xSqlServerLogin. One of the properties
passed to it in dsc is the login type. Perhaps that can be passed to the
password check method to select the correct way to connect

**Comment by johlju** [comment] 2017-02-01 17:45
Ah, okay. The `LoginType` parameter is used to tell what type of account the resource is changing. Not how to connect. There is no `Credential`  parameter that can be used to impersonate a login, of any kind, to the SQL Server. And to use your suggested method we would need a `CredentialLoginType` parameter as well. That could work. That would also mean that we would support PowerShell 4.0. But it is a lot of work to get this work done for all resources. I don't see that happening.

Currently to use xSQLServerLogin (and most resources) you need to use the built-in parameter `PsDscRunAsCredential` and assign the Windows authentication credentials to use to logon to the SQL Server which have the correct permission to change the login specified in the resource. `PsDscRunAsCredential` comes with PowerShell 5.x.
https://msdn.microsoft.com/en-us/powershell/dsc/runasuser

**Comment by johlju** [comment] 2017-02-01 17:47
Do you think `PsDscRunAsCredential` will work for you?

**Comment by iyoumans** [comment] 2017-02-10 13:11
I'm hitting this issue trying to run xSQLAOGroupEnsure to create an availability group.  I'm passing in a PSCredential for a domain account and getting the "bad username or password" error.  Passing in PsDscRunAsCredential doesn't help.

**Comment by randomnote1** [comment] 2017-02-10 19:28
Could you try with the new xSQLServerAlwaysOnAvailabilityGroup? This will replace AOgroupEnsure. I'm currently working on a new resource to build the replicas.

**Comment by iyoumans** [comment] 2017-02-10 20:10
Got this error with xSQLServerAlwaysOnAvailabilityGroup: Creating the availability group 'myavg' failed with the error 'Microsoft.SqlServer.Management.Smo.SmoException: The current instance 'localhost\myinst' must be included as an availability replica to create the availability group 'myavg'.

**Comment by doug-reimer** [comment] 2017-03-10 05:02
I'm also encountering a requirement for SQL Login support from the Connect-SQL helper function as the Test-TargetResource for the xSQLServerLogin resource fails on a password validation (of the SQL Login).

If as you suggest, we add an optional CredentialLoginType parameter to the Connect-SQL helper function, I think we would be able to do this relatively non-disruptively (wouldn't necessarily need to update other resources).  

Something like:

```
[ValidateSet("Windows","SQL")]
[System.String]
$CredentialLoginType`

if ($SetupCredential)
{
    
    $sql = New-Object Microsoft.SqlServer.Management.Smo.Server
    
    if ($CredentialLoginType -eq "SQL") 
    {
        $sql.ConnectionContext.LoginSecure = $false
        $sql.ConnectionContext.Login = $SetupCredential.GetNetworkCredential().UserName
        $sql.ConnectionContext.SecurePassword = $SetupCredential.Password
    }
    else 
    {
        $sql.ConnectionContext.ConnectAsUser = $true
        $sql.ConnectionContext.ConnectAsUserPassword = $SetupCredential.GetNetworkCredential().Password
        $sql.ConnectionContext.ConnectAsUserName = $SetupCredential.GetNetworkCredential().UserName
    }
    $sql.ConnectionContext.ServerInstance = $connectSQL
    $sql.ConnectionContext.connect()
}
```

I don't know enough about some of the other resources do know for sure what the impact would be, but I think this would be relatively easy.

**Comment by johlju** [comment] 2017-03-10 08:44
Yes that will work for the `Connect-Sql` helper function, but also setting the `$CredentialLoginType` to the default value of `'Windows'` so that it is not a breaking change.
The resources could use the same parameter name as `Connect-Sql`, or they could use a Boolean parameter, for example `$UseSqlAuthentication` with a default value of `$false` so there is no breaking change there either.
All the resources (like xSQLServerLogin) must also add the `$SetupCredential` parameter for this to work.

There will then be four different ways to authenticate.

* SYSTEM account - Default for WMF 4.0 and WMF 5.0.
* Built-in parameter `PsDcsRunAsCredential` - Optional for WMF 5.0, if set, the resource is run as this user.
* Windows authentication using `$SourceCredential` - If set, should impersonate using this user.
* SQL authentication using `$SourceCredential` and `$UseSqlAuthentication` - If set, should connect using this sql login.

If that is done, then we have WMF 4.0 support as well.

**Comment by johlju** [comment] 2017-03-10 08:50
Same issue for xSQLServerSetup, see issue #139

**Comment by johlju** [comment] 2017-06-06 08:31
We no longer should try to get WMF 4.0 support. So I think authenticate option 3 is today out of scope. For this PsDscRunAsCredential should be used.  What's missing is SQL authentication. I will change this issue title to reflect that this issue is to get SQL Authentication support for all resources.

**Comment by johlju** [comment] 2022-07-22 07:46
This issue is hit when using the username format `DOMAIN\user`. If switching to `user@domain` , e,g, `sqluser@mydomain.local`, then then we don't get the error `The user name or password is incorrect.`.

**Comment by johlju** [comment] 2022-07-22 07:56
See more information in issue https://github.com/dsccommunity/SqlServerDsc/issues/1223. Closing this issue, if there is still a problem that need to be addressed. Please open a new issue.

**Closed by johlju** 2022-07-22 07:56 UTC
Labels: enhancement, help wanted
