### ISSUE TITLE
SqlSetup: Unable to install 32-bit edition of SQL Server on 64-bit OS

### ISSUE THREAD

**Issue by rowlanch** [dsccommunity/SqlServerDsc#392] opened 2017-02-17 22:33 UTC
**Details of the scenario you try and problem that is occurring:**
I am attempting to install SQL Server 2014 Standard on Windows Server 2012 R2.  An error occurs during execution of the xSQLServerSetup resource:

Cannot find path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\SQL' because it does not exist.
    + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\...tance Names\SQL:) [], CimException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand
    + PSComputerName        : localhost

However, the SQL Server services are installed.  But I am unable to run the xSQLServerFirewall resource to open up the necessary firewall ports.  

Any suggestions on a possible fix?

**The DSC configuration that is using the resource (as detailed as possible):**
My script is as follows: 
```
#requires -Version 5

[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidUsingConvertToSecureStringWithPlainText", "")]
param ()

Configuration SQLServerSimple
{
    
    Import-DscResource -Module PSDesiredStateConfiguration, xSQLServer, xStorage

    Node $AllNodes.NodeName
    {
        
        # Set LCM to reboot if needed
        LocalConfigurationManager
        {
            # DebugMode = "ForceModuleImport"
            DebugMode = "All"
            RebootNodeIfNeeded = $true            
        }

        xMountImage SQLServerISO {
            ImagePath = $Node.ISOPath
            DriveLetter = $Node.ISODriveLetter
            Ensure = "Present"
        }

        xWaitForVolume ISOVolume {
            DriveLetter = $Node.ISODriveLetter
            DependsOn = "[xMountImage]SQLServerISO"
        }

        WindowsFeature NET-Framework-Core
        {
            Name = "NET-Framework-Core"
            Ensure = "Present"
        }

		# Install .NET 4.5
		WindowsFeature NET-Framework-45-Core 
		{ 
            Name = "NET-Framework-45-Core" 
			Ensure = "Present" 
            DependsOn = "[WindowsFeature]NET-Framework-Core"
        }
       
        if($Node.Features -ne "")
        {
        
            xSqlServerSetup ($Node.NodeName + $Node.InstanceName)
            {
                DependsOn = @('[WindowsFeature]NET-Framework-45-Core', '[xWaitForVolume]ISOVolume') 
                SourcePath = $Node.SourcePath
                SetupCredential = $Node.SetupCredential
                ForceReboot = $true
                InstanceName = $Node.InstanceName
                Features = $Node.Features
                SQLCollation  = "SQL_Latin1_General_CP1_CI_AS"
                InstallSharedDir = "E:\Program Files\Microsoft SQL Server"
                InstallSharedWOWDir = "E:\Program Files (x86)\Microsoft SQL Server"
                InstanceDir = "E:\Program Files\Microsoft SQL Server"
                InstallSQLDataDir = "E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data"
                SQLUserDBDir = "E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data\User"
                SQLUserDBLogDir = "E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data\User"
                SQLTempDBDir = "E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data\Temp"
                SQLTempDBLogDir = "E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data\Temp"
                SQLBackupDir = "E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data\Backup"
            }
                
            xSqlServerFirewall ($Node.NodeName + $Node.InstanceName)
            {
                DependsOn = ("[xSqlServerSetup]" + $Node.NodeName + $Node.InstanceName)
                SourcePath = $Node.SourcePath
                InstanceName = $Node.InstanceName
                Features = "SQLENGINE"  
                
            }
        
        }
        
    }

}

$InstallerCredential = Get-Credential "Administrator"

$ConfigurationData = @{
    AllNodes = @(
        @{
            NodeName = "*"
            PSDscAllowPlainTextPassword = $true
        }
        @{
            NodeName = "localhost"
            InstanceName = "MSSQLSERVER"
            Features = "SQLENGINE"
			SetupCredential = $InstallerCredential
            
            ISOPath = "c:\Install\en_sql_server_2014_standard_edition_with_service_pack_2_x86_dvd_8961302.iso"
            ISODriveLetter = "I:"
            SourcePath = "I:"

            
            
            
        }
    )
}


SQLServerSimple -ConfigurationData $ConfigurationData

Start-DscConfiguration -Path .\SQLServerSimple -Wait -Verbose -Force
```

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
OS:  Windows Server 2012 R2
SQL Server:  2014 Standard
Powershell:  5

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
xSQLServer:  5

**Comment by johlju** [comment] 2017-02-18 10:36
Hmm... Maybe there is a bug when installing a default instance. Might be that the particular key in the registry does not exist when installing the default instance. Let me verify that.

**Comment by johlju** [comment] 2017-02-18 14:05
I can't reproduce this. After xSQLServerSetup has finished, there is a correct record in the registry. I'm installing SQL2014SP1 (Enterprise, but should be no difference to Standard). OS is Windows Server 2012 R2, PowerShell is 5.0. Using xSQLServer v5.0.0.0.

Running the command:
```
Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\SQL'
```
Is getting the expected output
```
MSSQLSERVER  : MSSQL12.MSSQLSERVER
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\Instance
               Names\SQL
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\Instance
               Names
PSChildName  : SQL
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry
```

Could you run the above command. Do you get the same error?
Could you please post the verbose logs from Start-DscConfiguration so we can see if there is any strange there?
Also is there any errors in the SQL Server "ERROR LOG" file?

In a separate note, not related to xSQLServerSetup, but make sure that you can access the image you mounted when you run xSQLServerFirewall. It needs access to the file 'setup.exe' to determine the version of SQL that is being configured. You force reboot in xSQLServerSetup, so you might loose the mount when configuration is restarted.

**Comment by rowlanch** [comment] 2017-02-19 20:57
@johlju thanks for taking a look. In reviewing the logs, I realized that i had the 32 bit SQL Server ISO and not the 64 bit.  I tried again with the 64 bit ISO and got a clean install.  

Per request, I've included the command output and logs below.

The result of Get-ItemProperty:
```
PS C:\Users\Administrator> Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\SQL'
Get-ItemProperty : Cannot find path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\SQL' because it does not exist.
At line:1 char:1
+ Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\...tance Names\SQL:String) [Get-ItemProperty], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand
```
The verbose logs:

```
PS C:\DSC> C:\DSC\SQLServerSimple.ps1


    Directory: C:\DSC\SQLServerSimple


Mode                LastWriteTime         Length Name                                                                                                                                                  
----                -------------         ------ ----                                                                                                                                                  
-a----        2/17/2017   2:11 PM           8340 localhost.mof                                                                                                                                         
-a----        2/17/2017   2:11 PM           1108 localhost.meta.mof                                                                                                                                    
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows
/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer WIN-FDM8TBM8O53 with user sid S-1-5-21-1491513544-3994653951-2973281701-500.
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ Start  Set      ]
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ Start  Resource ]  [[xMountImage]SQLServerISO]
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ Start  Test     ]  [[xMountImage]SQLServerISO]
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xMountImage]SQLServerISO] Test-TargetResource: Testing Mounted Drive for image file 'I:'.
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xMountImage]SQLServerISO] Get-TargetResource: Getting Mounted Drive for image file 'c:\Install\en_sql_server_2014_standard_edition_with_service
_pack_2_x86_dvd_8961302.iso'.
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xMountImage]SQLServerISO] Test-TargetResource: The image file 'c:\Install\en_sql_server_2014_standard_edition_with_service_pack_2_x86_dvd_89613
02.iso' is not mounted to drive 'I' but should be. Change required.
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ End    Test     ]  [[xMountImage]SQLServerISO]  in 0.1090 seconds.
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ Start  Set      ]  [[xMountImage]SQLServerISO]
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xMountImage]SQLServerISO] Set-TargetResource: Setting Mounted Drive for image file 'c:\Install\en_sql_server_2014_standard_edition_with_service
_pack_2_x86_dvd_8961302.iso'.
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xMountImage]SQLServerISO] Get-TargetResource: Getting Mounted Drive for image file 'c:\Install\en_sql_server_2014_standard_edition_with_service
_pack_2_x86_dvd_8961302.iso'.
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xMountImage]SQLServerISO] Set-TargetResource: The image file 'c:\Install\en_sql_server_2014_standard_edition_with_service_pack_2_x86_dvd_896130
2.iso' is being mounted as drive 'I'.
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ End    Set      ]  [[xMountImage]SQLServerISO]  in 0.6410 seconds.
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ End    Resource ]  [[xMountImage]SQLServerISO]
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ Start  Resource ]  [[xWaitForVolume]ISOVolume]
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ Start  Test     ]  [[xWaitForVolume]ISOVolume]
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xWaitForVolume]ISOVolume] Test-TargetResource: Teting Wait for Volume status on volume 'I:'.
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xWaitForVolume]ISOVolume] Test-TargetResource: Found volume 'I'.
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ End    Test     ]  [[xWaitForVolume]ISOVolume]  in 1.1720 seconds.
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ Skip   Set      ]  [[xWaitForVolume]ISOVolume]
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ End    Resource ]  [[xWaitForVolume]ISOVolume]
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ Start  Resource ]  [[WindowsFeature]NET-Framework-Core]
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ Start  Test     ]  [[WindowsFeature]NET-Framework-Core]
VERBOSE: [WIN-FDM8TBM8O53]:                            [[WindowsFeature]NET-Framework-Core] The operation 'Get-WindowsFeature' started: NET-Framework-Core
VERBOSE: [WIN-FDM8TBM8O53]:                            [[WindowsFeature]NET-Framework-Core] The operation 'Get-WindowsFeature' succeeded: NET-Framework-Core
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ End    Test     ]  [[WindowsFeature]NET-Framework-Core]  in 0.5320 seconds.
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ Skip   Set      ]  [[WindowsFeature]NET-Framework-Core]
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ End    Resource ]  [[WindowsFeature]NET-Framework-Core]
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ Start  Resource ]  [[WindowsFeature]NET-Framework-45-Core]
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ Start  Test     ]  [[WindowsFeature]NET-Framework-45-Core]
VERBOSE: [WIN-FDM8TBM8O53]:                            [[WindowsFeature]NET-Framework-45-Core] The operation 'Get-WindowsFeature' started: NET-Framework-45-Core
VERBOSE: [WIN-FDM8TBM8O53]:                            [[WindowsFeature]NET-Framework-45-Core] The operation 'Get-WindowsFeature' succeeded: NET-Framework-45-Core
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ End    Test     ]  [[WindowsFeature]NET-Framework-45-Core]  in 0.4060 seconds.
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ Skip   Set      ]  [[WindowsFeature]NET-Framework-45-Core]
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ End    Resource ]  [[WindowsFeature]NET-Framework-45-Core]
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ Start  Resource ]  [[xSQLServerSetup]localhostMSSQLSERVER]
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ Start  Test     ]  [[xSQLServerSetup]localhostMSSQLSERVER]
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xSQLServerSetup]localhostMSSQLSERVER] 2017-02-17_14-11-22: Using path: I:\setup.exe
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xSQLServerSetup]localhostMSSQLSERVER] 2017-02-17_14-11-23: Features found: ''
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ End    Test     ]  [[xSQLServerSetup]localhostMSSQLSERVER]  in 0.9680 seconds.
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ Start  Set      ]  [[xSQLServerSetup]localhostMSSQLSERVER]
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xSQLServerSetup]localhostMSSQLSERVER] 2017-02-17_14-11-23: Using path: I:\setup.exe
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xSQLServerSetup]localhostMSSQLSERVER] 2017-02-17_14-11-23: Using path: I:\setup.exe
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xSQLServerSetup]localhostMSSQLSERVER] 2017-02-17_14-11-24: Starting setup using arguments: /ACTION="Install" /INSTANCEDIR="E:\Program Files\Mic
rosoft SQL Server" /SQLUSERDBDIR="E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data\User" /AGTSVCSTARTUPTYPE="Automatic" /IACCEPTSQLSERVERLICENSETERMS="True" /SQLTEMPDBLOGDIR="E:\Pr
ogram Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data\Temp" /INSTALLSHAREDWOWDIR="E:\Program Files (x86)\Microsoft SQL Server" /QUIET="True" /INSTANCENAME="MSSQLSERVER" /SQLBACKUPDIR="E:\Pro
gram Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data\Backup" /SQLUSERDBLOGDIR="E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data\User" /SQLSYSADMINACCOUNTS="Administrator"
 /SQLTEMPDBDIR="E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data\Temp" /SQLCOLLATION="SQL_Latin1_General_CP1_CI_AS" /FEATURES=SQLENGINE /INSTALLSQLDATADIR="E:\Program Files\Microso
ft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data" /INSTALLSHAREDDIR="E:\Program Files\Microsoft SQL Server"
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xSQLServerSetup]localhostMSSQLSERVER] 2017-02-17_14-11-25: Process matching path 'I:\setup.exe' started in process ID 540
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xSQLServerSetup]localhostMSSQLSERVER] 2017-02-17_14-20-38: Using path: I:\setup.exe
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xSQLServerSetup]localhostMSSQLSERVER] Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM Win3
2_Service WHERE Name = 'MSSQLSERVER','queryDialect' = WQL,'namespaceName' = root\cimv2'.
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xSQLServerSetup]localhostMSSQLSERVER] Operation 'Query CimInstances' complete.
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xSQLServerSetup]localhostMSSQLSERVER] Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM Win3
2_Service WHERE Name = 'SQLSERVERAGENT','queryDialect' = WQL,'namespaceName' = root\cimv2'.
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xSQLServerSetup]localhostMSSQLSERVER] Operation 'Query CimInstances' complete.
Cannot find path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\SQL' because it does not exist.
    + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\...tance Names\SQL:) [], CimException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand
    + PSComputerName        : localhost
 
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xSQLServerSetup]localhostMSSQLSERVER] 2017-02-17_14-20-41: Detecting replication feature (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\\Config
urationState)
Cannot find path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\ConfigurationState' because it does not exist.
    + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\...figurationState:) [], CimException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand
    + PSComputerName        : localhost
 
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xSQLServerSetup]localhostMSSQLSERVER] 2017-02-17_14-20-41: Replication feature not detected
You cannot call a method on a null-valued expression.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : InvokeMethodOnNull
    + PSComputerName        : localhost
 
Cannot find path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\Setup' because it does not exist.
    + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\...QL Server\Setup:) [], CimException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand
    + PSComputerName        : localhost
 
You cannot call a method on a null-valued expression.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : InvokeMethodOnNull
    + PSComputerName        : localhost
 
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xSQLServerSetup]localhostMSSQLSERVER] 2017-02-17_14-20-43: Connected to SQL localhost
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xSQLServerSetup]localhostMSSQLSERVER] 2017-02-17_14-20-45: Clustered instance not detected
VERBOSE: [WIN-FDM8TBM8O53]:                            [[xSQLServerSetup]localhostMSSQLSERVER] 2017-02-17_14-20-46: Features found: 'SQLENGINE'
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ End    Set      ]  [[xSQLServerSetup]localhostMSSQLSERVER]  in 563.0640 seconds.
The PowerShell DSC resource '[xSQLServerSetup]localhostMSSQLSERVER' with SourceInfo 'C:\DSC\SQLServerSimple.ps1::51::13::xSqlServerSetup' threw one or more non-terminating errors while running the 
Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
 
VERBOSE: [WIN-FDM8TBM8O53]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 569.826 seconds


```

SQL Server Log:

```
Overall summary:
  Final result:                  Passed
  Exit code (Decimal):           0
  Start time:                    2017-02-17 14:11:45
  End time:                      2017-02-17 14:20:18
  Requested action:              Install

Machine Properties:
  Machine name:                  WIN-FDM8TBM8O53
  Machine processor count:       4
  OS version:                    Windows Server 2012
  OS service pack:               
  OS region:                     United States
  OS language:                   English (United States)
  OS architecture:               x64
  Process architecture:          32 Bit
  OS clustered:                  No

Product features discovered:
  Product              Instance             Instance ID                    Feature                                  Language             Edition              Version         Clustered  Configured

Package properties:
  Description:                   Microsoft SQL Server 2014 
  ProductName:                   SQL Server 2014
  Type:                          RTM
  Version:                       12
  Installation location:         I:\x86\setup\
  Installation edition:          Standard

  Slipstream:                    True
  SP Level                       2

Product Update Status:
  Success: KB 3171021

Product Updates Selected for Installation:
  Title:                         Microsoft SQL Server 2014  with SP2
  Knowledge Based Article:       KB 3171021
  Version:                       12.2.5000.0
  Architecture:                  x86
  Language:                      1033

  Update Source:                 Slipstream


User Input Settings:
  ACTION:                        Install
  ADDCURRENTUSERASSQLADMIN:      false
  AGTSVCACCOUNT:                 NT Service\SQLSERVERAGENT
  AGTSVCPASSWORD:                *****
  AGTSVCSTARTUPTYPE:             Automatic
  ASBACKUPDIR:                   Backup
  ASCOLLATION:                   Latin1_General_CI_AS
  ASCONFIGDIR:                   Config
  ASDATADIR:                     Data
  ASLOGDIR:                      Log
  ASPROVIDERMSOLAP:              1
  ASSERVERMODE:                  MULTIDIMENSIONAL
  ASSVCACCOUNT:                  <empty>
  ASSVCPASSWORD:                 <empty>
  ASSVCSTARTUPTYPE:              Automatic
  ASSYSADMINACCOUNTS:            <empty>
  ASTEMPDIR:                     Temp
  BROWSERSVCSTARTUPTYPE:         Disabled
  CLTCTLRNAME:                   <empty>
  CLTRESULTDIR:                  <empty>
  CLTSTARTUPTYPE:                0
  CLTSVCACCOUNT:                 <empty>
  CLTSVCPASSWORD:                <empty>
  CLTWORKINGDIR:                 <empty>
  COMMFABRICENCRYPTION:          0
  COMMFABRICNETWORKLEVEL:        0
  COMMFABRICPORT:                0
  CONFIGURATIONFILE:             C:\Program Files (x86)\Microsoft SQL Server\120\Setup Bootstrap\Log\20170217_141126\ConfigurationFile.ini
  CTLRSTARTUPTYPE:               0
  CTLRSVCACCOUNT:                <empty>
  CTLRSVCPASSWORD:               <empty>
  CTLRUSERS:                     <empty>
  ENABLERANU:                    false
  ENU:                           true
  ERRORREPORTING:                false
  FEATURES:                      SQLENGINE
  FILESTREAMLEVEL:               0
  FILESTREAMSHARENAME:           <empty>
  FTSVCACCOUNT:                  <empty>
  FTSVCPASSWORD:                 <empty>
  HELP:                          false
  IACCEPTSQLSERVERLICENSETERMS:  true
  INDICATEPROGRESS:              false
  INSTALLSHAREDDIR:              E:\Program Files\Microsoft SQL Server
  INSTALLSHAREDWOWDIR:           E:\Program Files (x86)\Microsoft SQL Server
  INSTALLSQLDATADIR:             E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data
  INSTANCEDIR:                   E:\Program Files\Microsoft SQL Server
  INSTANCEID:                    MSSQLSERVER
  INSTANCENAME:                  MSSQLSERVER
  ISSVCACCOUNT:                  NT AUTHORITY\Network Service
  ISSVCPASSWORD:                 <empty>
  ISSVCSTARTUPTYPE:              Automatic
  MATRIXCMBRICKCOMMPORT:         0
  MATRIXCMSERVERNAME:            <empty>
  MATRIXNAME:                    <empty>
  NPENABLED:                     0
  PID:                           *****
  QUIET:                         true
  QUIETSIMPLE:                   false
  ROLE:                          
  RSINSTALLMODE:                 DefaultNativeMode
  RSSHPINSTALLMODE:              DefaultSharePointMode
  RSSVCACCOUNT:                  <empty>
  RSSVCPASSWORD:                 <empty>
  RSSVCSTARTUPTYPE:              Automatic
  SAPWD:                         <empty>
  SECURITYMODE:                  <empty>
  SQLBACKUPDIR:                  E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data\Backup
  SQLCOLLATION:                  SQL_Latin1_General_CP1_CI_AS
  SQLSVCACCOUNT:                 NT Service\MSSQLSERVER
  SQLSVCPASSWORD:                <empty>
  SQLSVCSTARTUPTYPE:             Automatic
  SQLSYSADMINACCOUNTS:           Administrator
  SQLTEMPDBDIR:                  E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data\Temp
  SQLTEMPDBLOGDIR:               E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data\Temp
  SQLUSERDBDIR:                  E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data\User
  SQLUSERDBLOGDIR:               E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data\User
  SQMREPORTING:                  false
  TCPENABLED:                    1
  UIMODE:                        Normal
  UpdateEnabled:                 true
  UpdateSource:                  Slipstream
  USEMICROSOFTUPDATE:            false
  X86:                           false

  Configuration file:            C:\Program Files (x86)\Microsoft SQL Server\120\Setup Bootstrap\Log\20170217_141126\ConfigurationFile.ini

Detailed results:
  Feature:                       Database Engine Services
  Status:                        Passed

  Feature:                       SQL Browser
  Status:                        Passed

  Feature:                       SQL Writer
  Status:                        Passed

  Feature:                       SQL Client Connectivity
  Status:                        Passed

  Feature:                       SQL Client Connectivity SDK
  Status:                        Passed

  Feature:                       Setup Support Files
  Status:                        Passed

Rules with failures:

Global rules:

Scenario specific rules:

Rules report file:               C:\Program Files (x86)\Microsoft SQL Server\120\Setup Bootstrap\Log\20170217_141126\SystemConfigurationCheck_Report.htm
```

**Comment by johlju** [comment] 2017-02-28 22:14
@rowlanch I'm happy you found the problem. Thanks for the logs. I changed the title to the actual error. I keep this issue open so the community can discuss 32-bit support on 64-bit OS (if so, most likely will be for Express installs). I label this as an enhancement in the mean time.

**Comment by johlju** [comment] 2017-02-28 22:18
Issue #39 has a solution for the above error. But tests should be made if there are more problems with 32-bit SQL on 64-bit OS.

**Comment by SphenicPaul** [comment] 2020-12-14 13:27
Is it worth closing both #39 and #392?

SQL Server installers from SQL 2016 onwards only come as a single installer/ISO - They only support 64-bit architectures and nolonger support 32-bit architectures (see [here](https://docs.microsoft.com/en-us/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server?view=sql-server-ver15)).

In addition, requirement for 32-bit installs on 64-bit OS/architecture will likely decrease as:
1) OS's becoming increasing **non**-supportive of 32-bit architectures
2) Users of SQL Server and the `SqlServerDsc` module upgrade to later versions of SQL Server that only support 64-bit architectures

Adding tests or functionality for supporting 32-bit architectures seems like it would provide limited benefit at this stage?

**Comment by johlju** [comment] 2020-12-24 10:30
I agree with @SphenicPaul, I'm closing this issue, but if anyone needs this support for 2012 R2 then I'm happy to review a PR for it.

**Closed by johlju** 2020-12-24 10:30 UTC
Labels: enhancement, help wanted
