### ISSUE TITLE
SQLSetup fails to apply update with SQL Server 2019

### ISSUE THREAD

**Issue by taschaal** [dsccommunity/SqlServerDsc#1475] opened 2020-03-11 15:45 UTC
#### Details of the scenario you tried and the problem that is occurring

Using DSC module to install SQL server 2019.  Fails when applying update.  Works if I don't add any update to UpdateSource folder.  Updates work fine with SQL Server 2017 

#### Verbose logs showing the problem

2020-03-11 08:56:21 Slp: Running Action: PackageExtractAction
(01) 2020-03-11 08:56:21 Slp: Sco: Directory C:\Windows\Temp\Developer_Edition\Updates\sqlserver2019-kb4527376-x64_01dcaca398f0c3380264078463fc1a6cc859ec7c.exe does not exist
(01) 2020-03-11 08:56:21 Slp: Running: C:\Windows\Temp\Developer_Edition\Updates\sqlserver2019-kb4527376-x64_01dcaca398f0c3380264078463fc1a6cc859ec7c.exe /x:"C:\Windows\TEMP\SQL Server 2019\Hotfix" /q
(01) 2020-03-11 08:56:27 Slp: Process returned 336
(01) 2020-03-11 08:56:27 Slp: Failed to extract package from the following location C:\Windows\Temp\Developer_Edition\Updates\sqlserver2019-kb4527376-x64_01dcaca398f0c3380264078463fc1a6cc859ec7c.exe, Error Code =336
(01) 2020-03-11 08:56:27 Slp: Error: Action "Microsoft.SqlServer.Configuration.SmartSetupExtension.PackageExtractAction" threw an exception during execution.
(01) 2020-03-11 08:56:27 Slp: The errors in action PackageExtractAction has been ignored.
(01) 2020-03-11 08:56:27 Slp: The following is an exception stack listing the exceptions in outermost to innermost order
(01) 2020-03-11 08:56:27 Slp: Inner exceptions are being indented
(01) 2020-03-11 08:56:27 Slp: 
(01) 2020-03-11 08:56:27 Slp: Exception type: Microsoft.SqlServer.Setup.Chainer.Workflow.ActionExecutionException
(01) 2020-03-11 08:56:27 Slp:     Message: 
(01) 2020-03-11 08:56:27 Slp:         SQL Server Setup was not able to extract requested product update C:\Windows\Temp\Developer_Edition\Updates\sqlserver2019-kb4527376-x64_01dcaca398f0c3380264078463fc1a6cc859ec7c.exe to C:\Windows\TEMP\SQL Server 2019\Hotfix. This can often happen when drive does not have enough space or the update package is corrupted. Click Retry to extract again or Cancel to exit out of Setup.
(01) 2020-03-11 08:56:27 Slp:     HResult : 0x851b0001
(01) 2020-03-11 08:56:27 Slp:         FacilityCode : 1307 (51b)
(01) 2020-03-11 08:56:27 Slp:         ErrorCode : 1 (0001)
(01) 2020-03-11 08:56:27 Slp:     Data: 
(01) 2020-03-11 08:56:27 Slp:       SQL.Setup.FailureCategory = ActionFailure
(01) 2020-03-11 08:56:27 Slp:     Stack: 
(01) 2020-03-11 08:56:27 Slp:         at Microsoft.SqlServer.Setup.Chainer.Workflow.ActionInvocation.ExecuteActionHelper(ActionWorker workerDelegate)
(01) 2020-03-11 08:56:27 Slp:         at Microsoft.SqlServer.Setup.Chainer.Workflow.ActionInvocation.ExecuteActionWithRetryHelper(WorkflowObject metaDb, ActionKey action, ActionMetadata actionMetadata, TextWriter statusStream)
(01) 2020-03-11 08:56:27 Slp:     Inner exception type: Microsoft.SqlServer.Configuration.SmartSetupExtension.PackageExtractionFailureException
(01) 2020-03-11 08:56:27 Slp:         Message: 
(01) 2020-03-11 08:56:27 Slp:                 SQL Server Setup was not able to extract requested product update C:\Windows\Temp\Developer_Edition\Updates\sqlserver2019-kb4527376-x64_01dcaca398f0c3380264078463fc1a6cc859ec7c.exe to C:\Windows\TEMP\SQL Server 2019\Hotfix. This can often happen when drive does not have enough space or the update package is corrupted. Click Retry to extract again or Cancel to exit out of Setup.
(01) 2020-03-11 08:56:27 Slp:         HResult : 0x851b0001
(01) 2020-03-11 08:56:27 Slp:                 FacilityCode : 1307 (51b)
(01) 2020-03-11 08:56:27 Slp:                 ErrorCode : 1 (0001)
(01) 2020-03-11 08:56:27 Slp:         Data: 
(01) 2020-03-11 08:56:27 Slp:           PackageLocation = C:\Windows\Temp\Developer_Edition\Updates\sqlserver2019-kb4527376-x64_01dcaca398f0c3380264078463fc1a6cc859ec7c.exe
(01) 2020-03-11 08:56:27 Slp:           ExtractLocation = C:\Windows\TEMP\SQL Server 2019\Hotfix
(01) 2020-03-11 08:56:27 Slp:           Result = 336
(01) 2020-03-11 08:56:27 Slp:           WatsonData = Microsoft.SqlServer.Configuration.SmartSetupExtension.PackageExtractionFailureException@1
(01) 2020-03-11 08:56:27 Slp:         Stack: 
(01) 2020-03-11 08:56:27 Slp:                 at Microsoft.SqlServer.Configuration.SmartSetupExtension.SfxcabExtractEngine.ExtractUpdate()
(01) 2020-03-11 08:56:27 Slp:                 at Microsoft.SqlServer.Configuration.SmartSetupExtension.PackageExtractAction.ExecuteAction(String actionId)
(01) 2020-03-11 08:56:27 Slp:                 at Microsoft.SqlServer.Chainer.Infrastructure.Action.Execute(String actionId, TextWriter errorStream)
(01) 2020-03-11 08:56:27 Slp:                 at Microsoft.SqlServer.Setup.Chainer.Workflow.ActionInvocation.<>c__DisplayClass2_0.<ExecuteActionWithRetryHelper>b__0()
(01) 2020-03-11 08:56:27 Slp:                 at Microsoft.SqlServer.Setup.Chainer.Workflow.ActionInvocation.ExecuteActionHelper(ActionWorker workerDelegate)
(01) 2020-03-11 08:56:27 Slp: ----------------------------------------------------------------------

#### Suggested solution to the issue

Manually running  C:\Windows\Temp\Developer_Edition\Updates\sqlserver2019-kb4527376-x64_01dcaca398f0c3380264078463fc1a6cc859ec7c.exe /x:"C:\Windows\TEMP\SQL Server 2019\Hotfix" /q  gives error "the application cannot be compressed to a system directory".  I don't receive this error with 2017 CU packages.  Perhaps the destination should be changed to a different directory  

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here


User Input Settings:
  ACTION:                        Install
  ADDCURRENTUSERASSQLADMIN:      false
  AGTSVCACCOUNT:                 <empty>
  AGTSVCPASSWORD:                <empty>
  AGTSVCSTARTUPTYPE:             Automatic
  ASBACKUPDIR:                   Backup
  ASCOLLATION:                   Latin1_General_CI_AS
  ASCONFIGDIR:                   Config
  ASDATADIR:                     Data
  ASLOGDIR:                      Log
  ASPROVIDERMSOLAP:              1
  ASSERVERMODE:                  TABULAR
  ASSVCACCOUNT:                  <empty>
  ASSVCPASSWORD:                 <empty>
  ASSVCSTARTUPTYPE:              Automatic
  ASSYSADMINACCOUNTS:            <empty>
  ASTELSVCACCT:                  <empty>
  ASTELSVCPASSWORD:              <empty>
  ASTELSVCSTARTUPTYPE:           0
  ASTEMPDIR:                     Temp
  BROWSERSVCSTARTUPTYPE:         Disabled
  CLTCTLRNAME:                   <empty>
  CLTRESULTDIR:                  <empty>
  CLTSTARTUPTYPE:                0
  CLTSVCACCOUNT:                 <empty>
  CLTSVCPASSWORD:                <empty>
  CLTWORKINGDIR:                 <empty>
  COMMFABRICENCRYPTION:          0
  COMMFABRICNETWORKLEVEL:        0
  COMMFABRICPORT:                0
  CONFIGURATIONFILE:             
  CTLRSTARTUPTYPE:               0
  CTLRSVCACCOUNT:                <empty>
  CTLRSVCPASSWORD:               <empty>
  CTLRUSERS:                     <empty>
  ENABLERANU:                    false
  ENU:                           true
  EXTSVCACCOUNT:                 <empty>
  EXTSVCPASSWORD:                <empty>
  FEATURES:                      SQLENGINE, CONN, BC, SDK
  FILESTREAMLEVEL:               0
  FILESTREAMSHARENAME:           <empty>
  FTSVCACCOUNT:                  <empty>
  FTSVCPASSWORD:                 <empty>
  HELP:                          false
  IACCEPTPYTHONLICENSETERMS:     false
  IACCEPTROPENLICENSETERMS:      false
  IACCEPTSQLSERVERLICENSETERMS:  true
  IACKNOWLEDGEENTCALLIMITS:      false
  INDICATEPROGRESS:              false
  INSTALLSHAREDDIR:              D:\MssqlServer\SQL2019
  INSTALLSHAREDWOWDIR:           D:\Program Files (x86)\Microsoft SQL Server
  INSTALLSQLDATADIR:             D:\VMLAB0138\MssqlServer\SQLData\Data
  INSTANCEDIR:                   D:\MssqlServer\SQL2019
  INSTANCEID:                    <empty>
  INSTANCENAME:                  MSSQLSERVER
  ISMASTERSVCACCOUNT:            NT AUTHORITY\Network Service
  ISMASTERSVCPASSWORD:           <empty>
  ISMASTERSVCPORT:               8391
  ISMASTERSVCSSLCERTCN:          <empty>
  ISMASTERSVCSTARTUPTYPE:        Automatic
  ISMASTERSVCTHUMBPRINT:         <empty>
  ISSVCACCOUNT:                  NT AUTHORITY\Network Service
  ISSVCPASSWORD:                 <empty>
  ISSVCSTARTUPTYPE:              Automatic
  ISTELSVCACCT:                  <empty>
  ISTELSVCPASSWORD:              <empty>
  ISTELSVCSTARTUPTYPE:           0
  ISWORKERSVCACCOUNT:            NT AUTHORITY\Network Service
  ISWORKERSVCCERT:               <empty>
  ISWORKERSVCMASTER:             <empty>
  ISWORKERSVCPASSWORD:           <empty>
  ISWORKERSVCSTARTUPTYPE:        Automatic
  MATRIXCMBRICKCOMMPORT:         0
  MATRIXCMSERVERNAME:            <empty>
  MATRIXNAME:                    <empty>
  MRCACHEDIRECTORY:              
  NPENABLED:                     0
  PBDMSSVCACCOUNT:               <empty>
  PBDMSSVCPASSWORD:              <empty>
  PBDMSSVCSTARTUPTYPE:           0
  PBENGSVCACCOUNT:               <empty>
  PBENGSVCPASSWORD:              <empty>
  PBENGSVCSTARTUPTYPE:           0
  PBPORTRANGE:                   <empty>
  PBSCALEOUT:                    false
  PID:                           *****
  QUIET:                         true
  QUIETSIMPLE:                   false
  ROLE:                          
  RSINSTALLMODE:                 DefaultNativeMode
  RSSVCACCOUNT:                  <empty>
  RSSVCPASSWORD:                 <empty>
  RSSVCSTARTUPTYPE:              Automatic
  SAPWD:                         *****
  SECURITYMODE:                  SQL
  SQLBACKUPDIR:                  D:\backup01\MssqlServer\SQLData\Backup
  SQLCOLLATION:                  Latin1_General_BIN
  SQLJAVADIR:                    <empty>
  SQLMAXDOP:                     0
  SQLMAXMEMORY:                  2147483647
  SQLMINMEMORY:                  0
  SQLSVCACCOUNT:                 *******
  SQLSVCINSTANTFILEINIT:         false
  SQLSVCPASSWORD:                *****
  SQLSVCSTARTUPTYPE:             Automatic
  SQLSYSADMINACCOUNTS:           Administrators
  SQLTELSVCACCT:                 <empty>
  SQLTELSVCPASSWORD:             <empty>
  SQLTELSVCSTARTUPTYPE:          0
  SQLTEMPDBDIR:                  D:\VMLAB0138_tempdb\MssqlServer\SQLData\Data
  SQLTEMPDBFILECOUNT:            0
  SQLTEMPDBFILEGROWTH:           -1
  SQLTEMPDBFILESIZE:             -1
  SQLTEMPDBLOGDIR:               D:\VMLAB0138_tempdb\MssqlServer\SQLData\Tlog
  SQLTEMPDBLOGFILEGROWTH:        -1
  SQLTEMPDBLOGFILESIZE:          -1
  SQLUSERDBDIR:                  D:\VMLAB0138\MssqlServer\SQLData\Data
  SQLUSERDBLOGDIR:               D:\VMLAB0138\MssqlServer\SQLData\Tlog
  SUPPRESSPAIDEDITIONNOTICE:     false
  SUPPRESSPRIVACYSTATEMENTNOTICE: false
  TCPENABLED:                    0
  UIMODE:                        Normal
  UpdateEnabled:                 true
  UpdateSource:                  C:\Windows\Temp\Developer_Edition\Updates
  USEMICROSOFTUPDATE:            false
  USESQLRECOMMENDEDMEMORYLIMITS: true
  X86:                           false

  Configuration file:            C:\Program Files\Microsoft SQL Server\150\Setup Bootstrap\Log\20200311_085611\ConfigurationFile.ini

#### SQL Server edition and version the target node is running
<!--
    To help with this information, please run this command in SQL:
    2019 Developer edition
-->

#### SQL Server PowerShell modules present on the target node
<!--
PS C:\Windows\system32>  Get-Module -Name '*sql*' -ListAvailable |  ft Name,Version,Path

Name         Version Path
----         ------- ----
SqlServerDsc 13.3.0  C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\13.3.0\SqlServerDsc.psd1

-->


#### The operating system the target node is running
<!--
    Please provide as much as possible about the target node, for example
    edition, version, build and language.
    On OS with WMF 5.1 the following command can help get this information.

    Get-ComputerInfo -Property @(
        'OsName',
        'OsOperatingSystemSKU',
        'OSArchitecture',
        'WindowsVersion',
        'WindowsBuildLabEx',
        'OsLanguage',
        'OsMuiLanguages')
OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2906.amd64fre.rs1_release_inmarket.190401-1809
OsLanguage           : en-US
OsMuiLanguages       : {en-US}


-->

#### Version and build of PowerShell the target node is running
<!--
    To help with this information, please run this command:
    $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.2879
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2879
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

-->

#### Version of the DSC module that was used
<!--
    To help with this information, please run this command:
    Get-Module -Name 'SqlServerDsc' -ListAvailable | ft Name,Version,Path
Name         Version Path
----         ------- ----
SqlServerDsc 13.3.0  C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\13.3.0\SqlServerDsc.psd1


-->

**Comment by johlju** [comment] 2020-03-13 20:01
This is a duplicate of issue #1472. Let's continue the discussion there.

**Closed by johlju** 2020-03-13 20:01 UTC
