### ISSUE TITLE
SqlSetup: Connect issues when using non standard ports

### ISSUE THREAD

**Issue by edycus** [dsccommunity/SqlServerDsc#429] opened 2017-03-08 18:28 UTC
First I install SQL with xSqlServerSetup
Then I Configure Networking with xSQLServerNetwork to set a non standard port 9999 (not really using this port)
Then I disable browser service.
Then I disabled Shared Memory Protocol in SQL Configuration

It runs fine the first time but when I run the Config again it errors on Test-Resource with Can't connect to instance. This is because it is attempting an connection on localhost/InstanceName with no port information.  

I recommend during the SQL connect function it checks to see if port is specified and uses that port. Maybe check for browser service and shared memory.

**Comment by wickedave** [comment] 2017-03-08 20:40
Hi,
I have the same exact problem. It was working well in the release 4 but since release 5, it seems to be broken.

**Comment by wickedave** [comment] 2017-03-09 14:02
I did a test with release 6 and didn't get the error. Seems it has been fixed.

**Comment by johlju** [comment] 2017-03-09 14:44
@wickedave Happy to hear that 6.0 solved your issue.

@edycus Could you test released version 6.0? See if the problem is gone like for @wickedave.
6.0 was release yesterday.

**Comment by edycus** [comment] 2017-03-10 20:17
I have tested and it did work for the first pass but after the disabling of the service I get this




VERBOSE: [SSVDBOLYTEST01]: LCM:  [ Start  Resource ]  [[xSQLServerSetup]installSqlServerTestSql1]
VERBOSE: [SSVDBOLYTEST01]: LCM:  [ Start  Test     ]  [[xSQLServerSetup]installSqlServerTestSql1]
VERBOSE: [SSVDBOLYTEST01]:                            [[xSQLServerSetup]installSqlServerTestSql1] Importing the module MSFT_xSQLServerSetup in force mode.
VERBOSE: [SSVDBOLYTEST01]:                            [[xSQLServerSetup]installSqlServerTestSql1] 2017-03-10_12-15-33: Using path: C:\Admin\DBA\DSCPowershellSQL\Software\SQL2014ENT\setup.exe
VERBOSE: [SSVDBOLYTEST01]:                            [[xSQLServerSetup]installSqlServerTestSql1] Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM Win32_Service WHERE Nam
e = 'MSSQL$TESTSQL1','queryDialect' = WQL,'namespaceName' = root\cimv2'.
VERBOSE: [SSVDBOLYTEST01]:                            [[xSQLServerSetup]installSqlServerTestSql1] Operation 'Query CimInstances' complete.
VERBOSE: [SSVDBOLYTEST01]:                            [[xSQLServerSetup]installSqlServerTestSql1] Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM Win32_Service WHERE Nam
e = 'SQLAgent$TESTSQL1','queryDialect' = WQL,'namespaceName' = root\cimv2'.
VERBOSE: [SSVDBOLYTEST01]:                            [[xSQLServerSetup]installSqlServerTestSql1] Operation 'Query CimInstances' complete.
VERBOSE: [SSVDBOLYTEST01]:                            [[xSQLServerSetup]installSqlServerTestSql1] 2017-03-10_12-15-33: Detecting replication feature (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL12.TESTSQL1\Configura
tionState)
VERBOSE: [SSVDBOLYTEST01]:                            [[xSQLServerSetup]installSqlServerTestSql1] 2017-03-10_12-15-33: Replication feature not detected
VERBOSE: [SSVDBOLYTEST01]:                            [[xSQLServerSetup]installSqlServerTestSql1] 2017-03-10_12-15-33: Client Connectivity Tools feature not detected
VERBOSE: [SSVDBOLYTEST01]:                            [[xSQLServerSetup]installSqlServerTestSql1] 2017-03-10_12-15-33: Client Connectivity Tools Backwards Compatibility feature not detected
VERBOSE: [SSVDBOLYTEST01]:                            [[xSQLServerSetup]installSqlServerTestSql1] 2017-03-10_12-15-33: Connected to SQL SSVDBOLYTEST01\TESTSQL1
The following exception occurred while trying to enumerate the collection: "Failed to connect to server SSVDBOLYTEST01\TESTSQL1.".
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : ExceptionInGetEnumerator
    + PSComputerName        : SSVdbOlyTest01
 
VERBOSE: [SSVDBOLYTEST01]:                            [[xSQLServerSetup]installSqlServerTestSql1] 2017-03-10_12-15-48: Clustered instance not detected
VERBOSE: [SSVDBOLYTEST01]:                            [[xSQLServerSetup]installSqlServerTestSql1] 2017-03-10_12-15-48: Features found: 'SQLENGINE,SSMS'
VERBOSE: [SSVDBOLYTEST01]: LCM:  [ End    Test     ]  [[xSQLServerSetup]installSqlServerTestSql1]  in 15.5610 seconds.
The PowerShell DSC resource '[xSQLServerSetup]installSqlServerTestSql1' with SourceInfo 'C:\Admin\DBA\DSCPowershellSQL\3 - SSVdbOlyTest01.ps1::364::13::xSqlServerSetup' threw one or more non-terminating errors while 
running the Test-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : SSVdbOlyTest01

**Comment by johlju** [comment] 2020-12-24 11:33
I close this issue and track this in the issue https://github.com/dsccommunity/SqlServerDsc/issues/329 instead. There should be a way to support this.

**Closed by johlju** 2020-12-24 11:33 UTC
Labels: bug, help wanted
